### ISSUE TITLE
PermissionDenied even when built with features=disable_automatic_asset_installation

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [zellij-org/zellij#1130]
`zellij --version`: zellij 0.25.0
`tput lines`: 72
`tput cols`: 271
`uname -av`: `Linux ALESSAND-F1E8 5.16.2-rt-rt19-x86_64 #5 SMP PREEMPT Tue Feb 15 19:20:22 CET 2022 x86_64 AMD Ryzen 5 3600 6-Core Processor AuthenticAMD GNU/Linux`

**Further information**
I've built zellij with `features=disable_automatic_asset_installation` and installed it in `/usr` but it will crash with
```
zellij options --simplified-ui true
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" }', src/install.rs:33:38
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

relevant part of `strace`

```
statx(AT_FDCWD, "/home/ale/.config/zellij", AT_STATX_SYNC_AS_STAT, STATX_ALL, {stx_mask=STATX_ALL|STATX_MNT_ID, stx_attributes=0, stx_mode=S_IFDIR|0755, stx_size=22, ...}) = 0
openat(AT_FDCWD, "/home/ale/.config/zellij/layouts/default", O_RDONLY|O_CLOEXEC) = -1 ENOENT (File o directory non esistente)
openat(AT_FDCWD, "/home/ale/.config/zellij/layouts/default.yaml", O_RDONLY|O_CLOEXEC) = -1 ENOENT (File o directory non esistente)
ioctl(0, TCGETS, {B38400 opost isig icanon echo ...}) = 0
getrandom("", 0, 0)                     = 0
getrandom("\xc8\x7e\xd8\x18\x8b\x2b\x3d\xa1\x11\x80\xe9\x26\xc7\x0e\x95\xc8\x2a\xfe\x98\x6b\xc7\xbc\x04\x1c\xab\xef\x83\xf0\x75\xe0\xfd\xeb"..., 2048, 0) = 2048
openat(AT_FDCWD, "/run/user/1000/zellij/0.25.0", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = -1 ENOENT (File o directory non esistente)
statx(AT_FDCWD, "/home/ale/.local/share/zellij", AT_STATX_SYNC_AS_STAT, STATX_ALL, 0x7ffc642d4300) = -1 ENOENT (File o directory non esistente)
statx(AT_FDCWD, "/usr/share/zellij", AT_STATX_SYNC_AS_STAT, STATX_ALL, {stx_mask=STATX_ALL|STATX_MNT_ID, stx_attributes=0, stx_mode=S_IFDIR|0700, stx_size=42, ...}) = 0
mmap(NULL, 548864, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x76fee3d19000
mmap(NULL, 585728, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x76fee3c8a000
openat(AT_FDCWD, "/usr/share/zellij/VERSION", O_RDONLY|O_CLOEXEC) = -1 EACCES (Permesso negato)
mkdir("/usr/share/zellij/plugins", 0777) = -1 EACCES (Permesso negato)
statx(AT_FDCWD, "/usr/share/zellij/plugins", AT_STATX_SYNC_AS_STAT, STATX_ALL, 0x7ffc642d4060) = -1 EACCES (Permesso negato)
```

I already have plugins in `/usr/share/zellij/plugins` and layouts in `/usr/share/zellij/layouts` because I've installed them with a gentoo ebuild
Also I have a config file in `~/.config/zellij/config.yaml`

```
tree /usr/share/zellij/
/usr/share/zellij/
├── layouts
│   ├── multiple_tabs_layout_htop_command.yaml
│   ├── multiple_tabs_layout.yaml
│   ├── run_htop_layout_with_plugins.yaml
│   └── run_htop_layout.yaml
├── plugins
│   ├── status-bar.wasm
│   ├── strider.wasm
│   └── tab-bar.wasm
└── VERSION
```

**Comment by a-kenji** [comment]
Hey! Thank you for reaching out. As discussed offline, do you mind sharing which layout you are loading?

**Comment by Alessandro-Barbieri** [comment]
I don't use a layout

**Comment by a-kenji** [comment]
This could potentially be an issue there, since zellij needs any layout at all. And if it has no assets, it has no layout. I'll look more into it tough!

**Comment by Alessandro-Barbieri** [comment]
Documentation say: `Falling back to an internal default layout`

**Comment by a-kenji** [comment]
Yes, that is correct. This feature changes things. This was mostly done so that distributions can ship it with different layouts, default configs and plugins, that go in to `/usr` for example. 
Layouts, configs and plugins are assets, that don't get included anymore. That being said I am not sure that this is the issue you are hitting.

> openat(AT_FDCWD, "/usr/share/zellij/VERSION", O_RDONLY|O_CLOEXEC) = -1 EACCES (Permesso negato)
mkdir("/usr/share/zellij/plugins", 0777) = -1 EACCES (Permesso negato)
statx(AT_FDCWD, "/usr/share/zellij/plugins", AT_STATX_SYNC_AS_STAT, STATX_ALL, 0x7ffc642d4060) = -1 EACCES (Permesso negato)

It seems we can't read the plugins and the version number at all from the permissions.

**Comment by Alessandro-Barbieri** [comment]
This point in the code is the issue
https://github.com/zellij-org/zellij/blob/2c3af751da2a8022f7ee05a9834bf1400a4a6c9e/src/commands.rs#L92

**Comment by a-kenji** [comment]
No, it's not the issue. It is the feature.
We should definitely improve the error message here.
But it is correct that this function is disabled for this feature.
Maybe more functions need to be disabled for this feature to be correct again.

**Comment by a-kenji** [comment]
What is the output of:
```
ls -la /usr/share/zellij/layouts
ls -la /usr/share/zellij/plugins
```
for you?

**Comment by Alessandro-Barbieri** [comment]
```
$ /bin/ls -la /usr/share/zellij/
totale 0
drwxr-xr-x. 1 root root    28 27 feb 22.38 .
drwxr-xr-x. 1 root root 21298 27 feb 22.13 ..
drwxr-xr-x. 1 root root   232 27 feb 22.38 layouts
drwxr-xr-x. 1 root root    78 27 feb 22.38 plugins
```

```
$ /bin/ls -la /usr/share/zellij/plugins
totale 1544
drwxr-xr-x. 1 root root     78 27 feb 22.38 .
drwxr-xr-x. 1 root root     28 27 feb 22.38 ..
-rw-r--r--. 1 root root 545535 27 feb 22.37 status-bar.wasm
-rw-r--r--. 1 root root 582975 27 feb 22.37 strider.wasm
-rw-r--r--. 1 root root 444598 27 feb 22.37 tab-bar.wasm
```
```
$ /bin/ls -la /usr/share/zellij/layouts
totale 16
drwxr-xr-x. 1 root root  232 27 feb 22.38 .
drwxr-xr-x. 1 root root   28 27 feb 22.38 ..
-rw-r--r--. 1 root root 1808 27 feb 22.37 multiple_tabs_layout_htop_command.yaml
-rw-r--r--. 1 root root 1748 27 feb 22.37 multiple_tabs_layout.yaml
-rw-r--r--. 1 root root  813 27 feb 22.37 run_htop_layout_with_plugins.yaml
-rw-r--r--. 1 root root  464 27 feb 22.37 run_htop_layout.yaml
```

**Comment by a-kenji** [comment]
Thank you!
Do you mind doing the same with:
```
/run/user/1000/zellij/0.25.0
```

and 
```
echo $XDG_RUNTIME_DIR
```
?

**Comment by Alessandro-Barbieri** [comment]
`/run/user/1000/zellij/0.25.0` is empty
`XDG_RUNTIME_DIR=/run/user/1000`
`XDG_CACHE_HOME` isn't set

**Comment by a-kenji** [comment]
Thank you!
What are the permissions of:
```
/run/user/1000/
```
?

And do you mind setting your `XDG_CACHE_HOME` to a test directory that has access rights?

**Comment by Alessandro-Barbieri** [comment]
```
$ /bin/ls -la /run/user/1000/
totale 0
drwx------. 8 ale  ale  240  1 mar 15.02 .
drwxr-xr-x. 4 root root  80  1 mar 15.00 ..
srw-rw-rw-. 1 ale  ale    0  1 mar 15.00 bus
drwx------. 3 ale  ale   60  1 mar 15.00 dbus-1
drwx------. 2 ale  ale   60  1 mar 15.00 emacs
prw-------. 1 ale  ale    0  1 mar 15.11 fish_universal_variables.notifier
drwx------. 2 ale  ale   60  1 mar 15.00 gnupg
srw-rw-rw-. 1 ale  ale    0  1 mar 15.00 pipewire-0
-rw-r-----. 1 ale  ale    0  1 mar 15.00 pipewire-0.lock
drwxr-xr-x. 2 ale  ale   80  1 mar 15.00 pulse
drwxr-xr-x. 5 ale  ale  140  1 mar 15.00 systemd
drwxr-xr-x. 3 ale  ale   60  1 mar 15.01 zellij
```

**Comment by a-kenji** [comment]
> You should default to `XDG_CACHE_HOME=$HOME/.cache` when `XDG_CACHE_HOME` isn't set

Yeah, that is what we do, I just wanted to be sure it is writeable.

> BTW I've tried settng it and the issue is still there

Do you mind removing the following folder and then trying it?
```
/run/user/1000/zellij
```

**Comment by Alessandro-Barbieri** [comment]
It's still the same

**Comment by Alessandro-Barbieri** [comment]
```
zellij setup --check
[Version]: "0.25.0"
[CONFIG DIR]: "/home/ale/.config/zellij"
[CONFIG FILE]: "/home/ale/.config/zellij/config.yaml"
[CONFIG FILE]: Well defined.
[DATA DIR]: "/home/ale/.local/share/zellij"
[PLUGIN DIR]: "/home/ale/.local/share/zellij/plugins"
[LAYOUT DIR]: "/home/ale/.config/zellij/layouts"
[SYSTEM DATA DIR]: "/usr/share/zellij"
[ARROW SEPARATOR]: 
 Is the [ARROW_SEPARATOR] displayed correctly?
 If not you may want to either start zellij with a compatible mode: 'zellij options --simplified-ui true'
 Or check the font that is in use:
 https://zellij.dev/documentation/compatibility.html#the-status-bar-fonts-dont-render-correctly
[MOUSE INTERACTION]:
 Can be temporarily disabled through pressing the [SHIFT] key.
 If that doesn't fix any issues consider to disable the mouse handling of zellij: 'zellij options --disable-mouse-mode'
[FEATURES]: []
[DOCUMENTATION]: zellij.dev/documentation
```

**Comment by CaptainBloodz** [comment]
Same here on gentoo with non root user:
zellij setup --check
[Version]: "0.26.0"
[CONFIG DIR]: "/home/luc/.config/zellij"
[CONFIG FILE]: "/home/luc/.config/zellij/config.yaml"
[CONFIG FILE]: Well defined.
[DATA DIR]: "/usr/share/zellij"
[PLUGIN DIR]: "/usr/share/zellij/plugins"
[LAYOUT DIR]: "/home/luc/.config/zellij/layouts"
[SYSTEM DATA DIR]: "/usr/share/zellij"
[ARROW SEPARATOR]: 
 Is the [ARROW_SEPARATOR] displayed correctly?
 If not you may want to either start zellij with a compatible mode: 'zellij options --simplified-ui true'
 Or check the font that is in use:
 https://zellij.dev/documentation/compatibility.html#the-status-bar-fonts-dont-render-correctly
[MOUSE INTERACTION]: 
 Can be temporarily disabled through pressing the [SHIFT] key.
 If that doesn't fix any issues consider to disable the mouse handling of zellij: 'zellij options --disable-mouse-mode'
[FEATURES]: []
[DOCUMENTATION]: zellij.dev/documentation

**Comment by a-kenji** [comment]
@CaptainBloodz,
Do you get the same error?

**Comment by CaptainBloodz** [comment]
```luc@amd64 ~ $ zellij 
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', src/install.rs:32:41
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace```

**Comment by CaptainBloodz** [comment]
```
UST_BACKTRACE=full zellij 
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', src/install.rs:32:41
stack backtrace:
   0:     0x558db649eefe - <unknown>
   1:     0x558db61faa4c - <unknown>
   2:     0x558db646b032 - <unknown>
   3:     0x558db64a0485 - <unknown>
   4:     0x558db64a1549 - <unknown>
   5:     0x558db64a0f28 - <unknown>
   6:     0x558db64a0ea6 - <unknown>
   7:     0x558db64a0e62 - <unknown>
   8:     0x558db61033c0 - <unknown>
   9:     0x558db6103692 - <unknown>
  10:     0x558db6657f06 - <unknown>
  11:     0x558db66542a5 - <unknown>
  12:     0x558db666219b - <unknown>
  13:     0x558db6652273 - <unknown>
  14:     0x558db649dac4 - <unknown>
  15:     0x558db6660b34 - <unknown>
  16:     0x7f82bfea3799 - __libc_start_main
  17:     0x558db61471ba - <unknown>
  18:                0x0 - <unknown>
```

**Comment by a-kenji** [comment]
Oh, my bad I meant to say `/tmp/zellij-${id}`, on my system it would be `/tmp/zellij-1000`.

**Comment by CaptainBloodz** [comment]
```
amd64 / # ll /tmp/zellij-*
/tmp/zellij-0:
total 12
drwx------ 2 root root 4096 mars  16 22:35 0.26.0
-rw-r--r-- 1 root root   56 mars  16 22:31 status-bar-tips.cache
drwx------ 2 root root 4096 mars  16 22:11 zellij-log

/tmp/zellij-1000:
total 4
drwx------ 2 luc luc 4096 mars  16 22:07 zellij-log

/tmp/zellij-250:
total 4
drwx------ 2 portage portage 4096 mars  16 21:19 zellij-log
amd64 / # cat /tmp/zellij-0/zellij-log/zellij.log 
INFO   |zellij_client            | 2022-03-16 22:11:07.749 [main      ] [zellij-client/src/lib.rs:121]: Starting Zellij client! 
INFO   |zellij_server            | 2022-03-16 22:11:07.757 [main      ] [zellij-server/src/lib.rs:188]: Starting Zellij server! 
INFO   |zellij_server::wasm_vm   | 2022-03-16 22:11:07.870 [wasm      ] [zellij-server/src/wasm_vm.rs:87]: Wasm main thread starts 
INFO   |zellij_client            | 2022-03-16 22:15:07.942 [main      ] [zellij-client/src/lib.rs:347]: Bye from Zellij! 
INFO   |zellij_server::wasm_vm   | 2022-03-16 22:15:07.942 [wasm      ] [zellij-server/src/wasm_vm.rs:226]: wasm main thread exits 
INFO   |zellij_client            | 2022-03-16 22:30:52.494 [main      ] [zellij-client/src/lib.rs:121]: Starting Zellij client! 
INFO   |zellij_server            | 2022-03-16 22:30:52.503 [main      ] [zellij-server/src/lib.rs:188]: Starting Zellij server! 
INFO   |zellij_server::wasm_vm   | 2022-03-16 22:30:52.555 [wasm      ] [zellij-server/src/wasm_vm.rs:87]: Wasm main thread starts 
INFO   |zellij_client            | 2022-03-16 22:31:42.081 [main      ] [zellij-client/src/lib.rs:121]: Starting Zellij client! 
INFO   |zellij_server            | 2022-03-16 22:31:42.087 [main      ] [zellij-server/src/lib.rs:188]: Starting Zellij server! 
INFO   |zellij_server::wasm_vm   | 2022-03-16 22:31:42.139 [wasm      ] [zellij-server/src/wasm_vm.rs:87]: Wasm main thread starts 
INFO   |zellij_client            | 2022-03-16 22:35:17.920 [main      ] [zellij-client/src/lib.rs:347]: Bye from Zellij! 
INFO   |zellij_server::wasm_vm   | 2022-03-16 22:35:17.920 [wasm      ] [zellij-server/src/wasm_vm.rs:170]: Bye from plugin 0 
INFO   |zellij_server::wasm_vm   | 2022-03-16 22:35:17.946 [wasm      ] [zellij-server/src/wasm_vm.rs:170]: Bye from plugin 1 
INFO   |zellij_server::wasm_vm   | 2022-03-16 22:35:17.946 [wasm      ] [zellij-server/src/wasm_vm.rs:226]: wasm main thread exits 
INFO   |zellij_client            | 2022-03-16 22:46:14.144 [main      ] [zellij-client/src/lib.rs:347]: Bye from Zellij! 
INFO   |zellij_server::wasm_vm   | 2022-03-16 22:46:14.144 [wasm      ] [zellij-server/src/wasm_vm.rs:170]: Bye from plugin 0 
INFO   |zellij_server::wasm_vm   | 2022-03-16 22:46:14.159 [wasm      ] [zellij-server/src/wasm_vm.rs:170]: Bye from plugin 1 
INFO   |zellij_server::wasm_vm   | 2022-03-16 22:46:14.160 [wasm      ] [zellij-server/src/wasm_vm.rs:226]: wasm main thread exits 
amd64 / # cat /tmp/zellij-1000/zellij-log/zellij.log
```
No idea what caused zellij-250...

**Comment by a-kenji** [comment]
> No idea what caused /tmp/zellij-250/...

Maybe the builder ran `zellij` ? And it maybe wasn't sandboxed?

**Comment by CaptainBloodz** [comment]
> > No idea what caused /tmp/zellij-250/...
> 
> Maybe the builder ran `zellij` ? And it maybe wasn't sandboxed?

```
amd64 / #  ll /var/log/portage/app-misc\:zellij-0.26.0\:20220316-174759.log.gz 
-rw-rw---- 1 portage portage 15242 mars  16 21:28 /var/log/portage/app-misc:zellij-0.26.0:20220316-174759.log.gz
```
Nice catch ;)

**Comment by a-kenji** [comment]
@CaptainBloodz 
Thank you for the help so far!
I did figure out this error. Do you mind testing the pr #1226 ?

I do suspect you will get another errror, but I am not sure.

**Comment by CaptainBloodz** [comment]
Lucky you,
Gentoo makes pr test easy.
Currently setting & rebuilding on 0.26.1...

**Comment by CaptainBloodz** [comment]
```
RUST_BACKTRACE=full zellij 

Error occurred in server:
Originating Thread(s):

Error: thread 'wasm' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }': zellij-server/src/wasm_vm.rs:95
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: start_thread
  12: __clone
```
Build warnings:
```
   Compiling zellij v0.26.0 (/var/tmp/portage/app-misc/zellij-0.26.0/work/zellij-0.26.0)
warning: unused import: `crate::install::populate_data_dir`
 --> src/commands.rs:1:5
  |
1 | use crate::install::populate_data_dir;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: unused import: `get_default_data_dir`
  --> src/commands.rs:20:13
   |
20 |     setup::{get_default_data_dir, Setup},
   |             ^^^^^^^^^^^^^^^^^^^^

warning: unused variable: `opts`
  --> src/commands.rs:90:27
   |
90 | fn install_default_assets(opts: &CliArgs) {
   |                           ^^^^ help: if this is intentional, prefix it with an underscore: `_opts`
   |
   = note: `#[warn(unused_variables)]` on by default

warning: function is never used: `populate_data_dir`
  --> src/install.rs:17:15
   |
17 | pub(crate) fn populate_data_dir(data_dir: &Path) {
   |               ^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default

warning: `zellij` (bin "zellij") generated 4 warnings
    Finished release [optimized] target(s) in 16m 27s
>>> Source compiled.
>>> Test phase [not enabled]: app-misc/zellij-0.26.0

>>> Install app-misc/zellij-0.26.0 into /var/tmp/portage/app-misc/zellij-0.26.0/image
 * cargo install --path ./ --root /var/tmp/portage/app-misc/zellij-0.26.0/image/usr --features disable_automatic_asset_installation
  Installing zellij v0.26.0 (/var/tmp/portage/app-misc/zellij-0.26.0/work/zellij-0.26.0)
warning: Environment variables are expected to use uppercase letters and underscores, the variable `CARGO_TARGET_x86_64_UNKNOWN_LINUX_GNU_RUSTFLAGS` will be ignored and have no effect
warning: Environment variables are expected to use uppercase letters and underscores, the variable `CARGO_TARGET_x86_64_UNKNOWN_LINUX_GNU_RUSTFLAGS` will be ignored and have no effect
warning: Environment variables are expected to use uppercase letters and underscores, the variable `CARGO_TARGET_x86_64_UNKNOWN_LINUX_GNU_RUSTFLAGS` will be ignored and have no effect
warning: Environment variables are expected to use uppercase letters and underscores, the variable `CARGO_TARGET_x86_64_UNKNOWN_LINUX_GNU_RUSTFLAGS` will be ignored and have no effect
warning: unused import: `crate::install::populate_data_dir`
 --> src/commands.rs:1:5
  |
1 | use crate::install::populate_data_dir;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: unused import: `get_default_data_dir`
  --> src/commands.rs:20:13
   |
20 |     setup::{get_default_data_dir, Setup},
   |             ^^^^^^^^^^^^^^^^^^^^

warning: unused variable: `opts`
  --> src/commands.rs:90:27
   |
90 | fn install_default_assets(opts: &CliArgs) {
   |                           ^^^^ help: if this is intentional, prefix it with an underscore: `_opts`
   |
   = note: `#[warn(unused_variables)]` on by default

warning: function is never used: `populate_data_dir`
  --> src/install.rs:17:15
   |
17 | pub(crate) fn populate_data_dir(data_dir: &Path) {
   |               ^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default

warning: `zellij` (bin "zellij") generated 4 warnings
    Finished release [optimized] target(s) in 10.34s
```

**Comment by a-kenji** [comment]
Awesome, thank you! That was the error I was expecting.

**Comment by a-kenji** [comment]
@CaptainBloodz,
Do you mind trying the pr out again?
I do believe it should work now.

**Comment by CaptainBloodz** [comment]
Previous pr removed, new one added:
```
luc@amd64 ~ $ RUST_BACKTRACE=full zellij 
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', src/install.rs:32:41
stack backtrace:
   0:     0x55d7b2f08efe - <unknown>
   1:     0x55d7b2c64a4c - <unknown>
   2:     0x55d7b2ed5032 - <unknown>
   3:     0x55d7b2f0a485 - <unknown>
   4:     0x55d7b2f0b549 - <unknown>
   5:     0x55d7b2f0af28 - <unknown>
   6:     0x55d7b2f0aea6 - <unknown>
   7:     0x55d7b2f0ae62 - <unknown>
   8:     0x55d7b2b6d3c0 - <unknown>
   9:     0x55d7b2b6d692 - <unknown>
  10:     0x55d7b30c1f06 - <unknown>
  11:     0x55d7b30be2a5 - <unknown>
  12:     0x55d7b30cc19b - <unknown>
  13:     0x55d7b30bc273 - <unknown>
  14:     0x55d7b2f07ac4 - <unknown>
  15:     0x55d7b30cab34 - <unknown>
  16:     0x7f850c6be799 - __libc_start_main
  17:     0x55d7b2bb11ba - <unknown>
  18:                0x0 - <unknown>
```

**Comment by a-kenji** [comment]
Are you sure this was built with the feature?

**Comment by CaptainBloodz** [comment]
> Are you sure this was built with the feature?

Snipplet from build script I didn't wrote:
```
src_configure() {
        local myfeatures=(
                disable_automatic_asset_installation
        )
        cargo_src_configure
}
```

**Comment by CaptainBloodz** [comment]
[22cff54](https://github.com/a-kenji/zellij/commit/22cff5439ca33c0beafd6a77c160959dff7fddf7) is the patch file applied here....

**Comment by Alessandro-Barbieri** [comment]
For the record I'm the maintainer of that ebuild

**Comment by a-kenji** [comment]
@Alessandro-Barbieri,
Can you confirm the same error after #1226 is applied?

Also do you mind trying:
```
zellij --data-dir /usr/share/zellij
```
with it?

**Comment by CaptainBloodz** [comment]
> For the record I'm the maintainer of that ebuild
No suprise we have similar issue;
Not sure it matters, but we have some # with dir & files rights.

**Comment by CaptainBloodz** [comment]
Could it be a clue the fact it works fine as root?
@Alessandro-Barbieri,
Are you testing as git manual build or via ebuild?

**Comment by a-kenji** [comment]
> Could it be a clue the fact it works fine as root?

Root should be able to create the directories, because it can set the permissions on those directories.

**Comment by CaptainBloodz** [comment]
Could there be any /etc/group thingie missing for non root user?

**Comment by Alessandro-Barbieri** [comment]
```
zellij --data-dir /usr/share/zellij

Error occurred in server:

  × Thread 'wasm' panicked.
  ├─▶ Originating Thread(s)
  │     1. ipc_server: NewClient
  │     2. pty_thread: NewTab
  │     3. screen_thread: NewTab
  │     4. plugin_thread: Load
  │
  ├─▶ At zellij-server/src/wasm_vm.rs:289:10
  ╰─▶ called `Result::unwrap()` on an `Err` value: PreopenedDirectoryNotFound("/usr/share/zellij/plugins/data/zellij:tab-bar")
  help: If you are seeing this message, it means that something went wrong.
        Please report this error to the github issue.
        (https://github.com/zellij-org/zellij/issues)

        Also, if you want to see the backtrace, you can set the `RUST_BACKTRACE` environment variable to `1`.
```

`/usr/share/zellij/plugins/data/` doesn't exist

**Comment by a-kenji** [comment]
Thank you! Do you mind trying the new push?

**Comment by Alessandro-Barbieri** [comment]
It worked

**Comment by Alessandro-Barbieri** [comment]
> Just to clarify: You still need to pass in the `data_dir` flag?

No

**Comment by a-kenji** [comment]
Thank you @CaptainBloodz and @Alessandro-Barbieri
For raising this issue and participating in solving it!
I hope the current main branch works for you now.
Please don't hesitate reaching out in the future.
