### ISSUE TITLE
stdin input before rendered crashes zellij

### ISSUE THREAD

**Issue by DieracDelta** [zellij-org/zellij#1134]
# In Case of Graphical or Performance Issues

1. Delete the contents of `/tmp/zellij-1000/zellij-log`, ie with `cd /tmp/zellij-1000/` and `rm -fr zellij-log/`
2. Run `zellij --debug`
3. Recreate your issue.
3. Quit Zellij immediately with ctrl-q (your bug should ideally still be visible on screen)

log output:

```
INFO   |zellij_client            | 2022-02-26 23:07:11.464 [main      ] [zellij-client/src/lib.rs:121]: Starting Zellij client!
INFO   |zellij_server            | 2022-02-26 23:07:11.466 [main      ] [zellij-server/src/lib.rs:188]: Starting Zellij server!
INFO   |zellij_server::wasm_vm   | 2022-02-26 23:07:11.517 [wasm      ] [zellij-server/src/wasm_vm.rs:86]: Wasm main thread starts
INFO   |zellij_server::wasm_vm   | 2022-02-26 23:07:11.520 [wasm      ] [zellij-server/src/wasm_vm.rs:225]: wasm main thread exits
```

# Basic information

`zellij --version`: on both 0.24.0 and 01f7f4f3d2a83b8f3af90d9e6a85371d988c9f2a (so, HEAD as of when this issue was created)
`tput lines`:67
`tput cols`: 126
`uname -av` or `ver`(Windows): Linux desktop 5.16.10 #1-NixOS SMP PREEMPT Wed Feb 16 11:58:51 UTC 2022 x86_64 GNU/Linux

List of programs you interact with as: N/A/none

# To reproduce

`zellij`

Then mash the keyboard immediately after. This results in unwrapping a none value with the following stack trace:

```
as
Error occurred in server:
Originating Thread(s):
1. stdin_handler_thread: AcceptInput
2. screen_thread: ClearScroll

Error: thread 'screen' panicked at 'called `Option::unwrap()` on a `None` value': zellij-server/src/screen.rs:1062
   0: zellij_utils::errors::handle_panic
   1: std::panicking::rust_panic_with_hook
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:610:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:500:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:139:18
   4: rust_begin_unwind
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
   5: core::panicking::panic_fmt
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
   6: core::panicking::panic
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:48:5
   7: zellij_server::screen::screen_thread_main
   8: std::sys_common::backtrace::__rust_begin_short_backtrace
   9: core::ops::function::FnOnce::call_once{{vtable.shim}}
  10: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/alloc/src/boxed.rs:1854:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/alloc/src/boxed.rs:1854:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys/unix/thread.rs:108:17
  11: start_thread
  12: clone
  ```

**Comment by raphCode** [comment]
See also my reproducer at: https://github.com/zellij-org/zellij/issues/805#issuecomment-1047332560
