### ISSUE TITLE
Unable to run zellij

### ISSUE THREAD

**Issue by pdgendt** [zellij-org/zellij#2861]
**Basic information**

`zellij --version`: `main` or `v0.38.2`
`stty size`: `80 344`
`uname -av` or `ver`(Windows): `Linux 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

**Further information**
```sh
$ RUST_BACKTRACE=1 cargo xtask run
    Finished dev [unoptimized + debuginfo] target(s) in 0.09s
     Running `target/debug/xtask run`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "protoc failed: resize.proto: This file contains proto3 optional fields, but --experimental_allow_proto3_optional was not set.\n" }', xtask/src/build.rs:70:18
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/result.rs:1791:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/result.rs:1113:23
   4: xtask::build::build
             at ./xtask/src/build.rs:68:13
   5: xtask::pipelines::run
             at ./xtask/src/pipelines.rs:130:9
   6: xtask::main
             at ./xtask/src/main.rs:66:40
   7: core::ops::function::FnOnce::call_once
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/ops/function.rs:507:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by imsnif** [comment]
Hey, this looks like you're compiling Zellij from source and have the wrong protoc version. Do you intend to develop Zellij? If so, please take a look at the `CONTRIBUTING.md` document for further build instructions.

Otherwise I'd recommend running a release version (eg. one installed with `cargo install --locked zellij`.

**Comment by pdgendt** [comment]
I installed it from source, because I was unable to run the released cargo version, however the error message is different:
```sh
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', /home/pdgendt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/zellij-client-0.38.2/src/lib.rs:193:44
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by imsnif** [comment]
From a cursory look, it seems like Zellij has an issue writing and/or creating the temporary folder on your system

**Comment by pdgendt** [comment]
The temporary folder can be created, also the log file:
```shell
$ find /tmp/zellij-1000
/tmp/zellij-1000
/tmp/zellij-1000/zellij-log
/tmp/zellij-1000/zellij-log/zellij.log

$ cat /tmp/zellij-1000/zellij-log/zellij.log
INFO   |zellij_client            | 2023-10-16 09:22:17.617 [main      ] [/home/pdgendt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/zellij-client-0.38.2/src/lib.rs:152]: Starting Zellij client!
```

I removed `~/.config/zellij` but the result is the same.

**Comment by pdgendt** [comment]
This folder does not seem to exist:

```shell
$ echo $XDG_RUNTIME_DIR
/run/user/1000/

$ find $XDG_RUNTIME_DIR
find: ‘/run/user/1000/’: No such file or directory
```

**Comment by imsnif** [comment]
I'd say that's the issue. Try creating it with read/write permissions for your user and I think that should do the trick.

**Comment by pdgendt** [comment]
That did the trick!

For reference:
```shell
$ sudo mkdir $XDG_RUNTIME_DIR
$ sudo chown $USER:$USER $XDG_RUNTIME_DIR
```

Maybe it would be nice to fallback to a `/tmp/` directory?

**Comment by pi12138** [comment]
That did the trick!
