### ISSUE TITLE
Build failure on 390x platform

### ISSUE THREAD

**Issue by jabir366** [zellij-org/zellij#3180]
# Build Error on s390x  platform on RHEL 9 

## Issue description
   The build if failing on s390x platform running on RHEL 9.3
## Minimal reproduction
  Run `RUST_BACKTRACE=1  cargo xtask build`
The output is
```
$ RUST_BACKTRACE=1  cargo xtask build
        Finished dev [unoptimized + debuginfo] target(s) in 0.10s
     Running `target/debug/xtask build`
thread 'main' panicked at xtask/src/build.rs:85:22:
called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "protoc failed: action.proto: This file contains proto3 optional fields, but --experimental_allow_proto3_optional was not set.\n" }
stack backtrace:
   0: rust_begin_unwind
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/result.rs:1653:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/result.rs:1077:23
   4: xtask::build::build
             at ./xtask/src/build.rs:83:17
   5: xtask::main
             at ./xtask/src/main.rs:57:42
   6: core::ops::function::FnOnce::call_once
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
## Other relevant information
output of `cat /etc/os-release`
```
NAME="Red Hat Enterprise Linux"
VERSION="9.3 (Plow)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="9.3"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Red Hat Enterprise Linux 9.3 (Plow)"
ANSI_COLOR="0;31"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:redhat:enterprise_linux:9::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 9"
REDHAT_BUGZILLA_PRODUCT_VERSION=9.3
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.3"
```
Protoc version
```
$ protoc --version
   libprotoc 3.14.0
```
CPU architecture
```
$ uname -m
   s390x
```

**Comment by lysliu** [comment]
There are two options for getting around this error:

Pass --experimental_allow_proto3_optional to protoc.
Make your filename (or a directory name) contain the string test_proto3_optional. This indicates that the proto file is specifically for testing proto3 optional support, so the check is suppressed.
These options are demonstrated below:

# One option:
$ protoc test.proto --cpp_out=. --experimental_allow_proto3_optional

# Another option:
$ cp test.proto test_proto3_optional.proto
$ protoc test_proto3_optional.proto --cpp_out=.
$
