### ISSUE TITLE
zellij not opening but crashed - "thread 'main' panicked at zellij-client/src/lib.rs:219:44"

### ISSUE THREAD

**Issue by aruprakshit** [zellij-org/zellij#3617]
2. Issues with the Zellij UI / behavior / crash

Please attach the files that were created in `/tmp/zellij-1000/zellij-log/` to the extent you are comfortable with.

```sh
 tail -f zellij.log

INFO   |zellij_client            | 2024-09-21 12:03:06.189 [main      ] [zellij-client/src/lib.rs:178]: Starting Zellij client!

INFO   |zellij_client            | 2024-09-21 12:03:37.797 [main      ] [zellij-client/src/lib.rs:178]: Starting Zellij client!
INFO   |zellij_client            | 2024-09-21 12:04:24.834 [main      ] [zellij-client/src/lib.rs:178]: Starting Zellij client!
```

**Basic information**

```sh
╭─arup at deadpool in ~/elxr-containers on main✘✘✘ 24-09-21 - 12:04:24
╰─⠠⠵ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.5 LTS
Release:        22.04
Codename:       jammy
╭─arup at deadpool in ~/elxr-containers on main✘✘✘ 24-09-21 - 12:05:04
╰─⠠⠵ uname -a
Linux deadpool 5.15.153.1-microsoft-standard-WSL2 #1 SMP Fri Mar 29 23:14:13 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
╭─arup at deadpool in ~/elxr-containers on main✘✘✘ 24-09-21 - 12:05:09
╰─⠠⠵ stty size
40 170
╭─arup at deadpool in ~/elxr-containers on main✘✘✘ 24-09-21 - 12:05:28
╰─⠠⠵ zellij --version
zellij 0.40.1
```

## Issue description

When I run ` zellij` I see a quick text appears, and then no session window. I am back to the window from where I ran the command. I checked the `zellij.log` it doesn't have anything printed about the error. So somehow I manged to get atleast to the see the text was comming and disappearing like below.

```sh
 zellij > ~/.stderr.log
thread 'main' panicked at zellij-client/src/lib.rs:219:44:
called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

## Minimal reproduction

I have it installed locally. Still wanted to check if the error is my setup. But I see when I run this `bash <(curl -L zellij.dev/launch)` I see the same issue as I said above.

## Other relevant information

I don't have.

**Comment by imsnif** [comment]
Seems like Zellij does not have permission to create this folder: https://docs.rs/directories/5.0.1/directories/struct.ProjectDirs.html#method.cache_dir

We use it for the IPC files to communicate between the Zellij client and server. Can't run without it...

**Comment by aruprakshit** [comment]
> Seems like Zellij does not have permission to create this folder: https://docs.rs/directories/5.0.1/directories/struct.ProjectDirs.html#method.cache_dir
> 
> We use it for the IPC files to communicate between the Zellij client and server. Can't run without it...

Ok. What do I need to do here? It was working, just after the upgrade of OS it broke.

**Comment by kakumarabhishek** [comment]
@hstaugaard thanks for your solution. This fixes the launch for me, but do you know how I can add this to my `.zshrc` along with the [autostart on shell creation](https://zellij.dev/documentation/integration#zsh)? The command for autostart on zsh is
`eval "$(zellij setup --generate-auto-start zsh)"`.

**Comment by nwtowers-matthew** [comment]
Same unwrap panic seems to still be present. I tried tracing the code to find out what the default value for ZELLIJ_SOCKET_DIR is but it's a bit too convoluted for me. Either way, there should probably be something that catches this and tells the user what the problem is (not to mention the Rust runtime error text is immediately cleared on exit, at least for me, so I had to capture it into a file to read it).

Nothing unusual about my setup that should lead to a permissions problem, and /tmp/zellij works fine. Anyone know what the default path is?
