### ISSUE TITLE
MacOS download not working

### ISSUE THREAD

**Issue by eschnett** [zellij-org/zellij#363]
I am using MacOS 11.2.3:
```
$ uname -a
Darwin redshift.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64 i386 MacBookPro15,1 Darwin
```

I downloaded and unpacked Zellij:
```
$ wget https://github.com/zellij-org/zellij/releases/download/v0.5.1/zellij-macos-x86_64.tar.gz
$ tar tvzf zellij-macos-x86_64.tar.gz
-rwxr-xr-x aram/aram   7821184 2021-04-23 04:41 zellij
```

This executable does not work:
```
$ ./zellij
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 20, kind: Other, message: "Not a directory" }', src/main.rs:51:47
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

```
$ env RUST_BACKTRACE=full ./zellij
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 20, kind: Other, message: "Not a directory" }', src/main.rs:51:47
stack backtrace:
   0:        0x10ffa4713 - __mh_execute_header
   1:        0x10fd6be8e - __mh_execute_header
   2:        0x10ffa404a - __mh_execute_header
   3:        0x10ffa3aef - __mh_execute_header
   4:        0x10ffa2e1d - __mh_execute_header
   5:        0x10ffc324a - __mh_execute_header
   6:        0x10ffc31b8 - __mh_execute_header
   7:        0x10ffc3160 - __mh_execute_header
   8:        0x11020645f - __mh_execute_header
   9:        0x110206ad5 - __mh_execute_header
  10:        0x1101e6833 - __mh_execute_header
  11:        0x10fce076a - __mh_execute_header
  12:        0x1101e5e44 - __mh_execute_header
```

**Comment by eschnett** [comment]
I see the same error when I build Zellij from source (`cargo install zellij`). However, I get a better backtrace:
```
$ env RUST_BACKTRACE=full zellij
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 20, kind: Other, message: "Not a directory" }', /Users/eschnett/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-0.5.1/src/main.rs:51:47
stack backtrace:
   0:        0x1013a2973 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h18cc31b07c2f1a67
   1:        0x10118803d - core::fmt::write::h24f8349e8e89c9af
   2:        0x1013a2296 - std::io::Write::write_fmt::hc54d7d6e95b15753
   3:        0x1013a1c39 - std::panicking::default_hook::{{closure}}::h11b550d560f5cc66
   4:        0x1013a1350 - std::panicking::rust_panic_with_hook::hf87bfc4afef21ea6
   5:        0x1013c49ea - std::panicking::begin_panic_handler::{{closure}}::h19ac9cd24a19b238
   6:        0x1013c4958 - std::sys_common::backtrace::__rust_end_short_backtrace::h5fc3f41df3517232
   7:        0x1013c4900 - _rust_begin_unwind
   8:        0x10164d91f - core::panicking::panic_fmt::habd0855285375977
   9:        0x10164df25 - core::option::expect_none_failed::ha58308d4da981532
  10:        0x101645415 - zellij::main::h87e462f59c9f00e5
  11:        0x1015f61ea - std::sys_common::backtrace::__rust_begin_short_backtrace::h04b88b22cb192a79
  12:        0x101640544 - _main
```

**Comment by a-kenji** [comment]
Thank you for filing this issue!

**Comment by qballer** [comment]
I've tested these files and they seem to work on my machine running the same version of mac, even though uname -a doesn't output "x86_64 i386 MacBookPro15,1 Darwin" part of things. I wonder why this is happening? I will try to test with some other people running mac to see if we can find out more about the issue.

**Comment by maximumstock** [comment]
Just a random guess, but could it be due to calling [`atomic_create_dir`](https://github.com/zellij-org/zellij/blob/main/src/common/utils/logging.rs#L16-L26) with `ZELLIJ_TMP_DIR`/`ZELLIJ_TMP_LOG_DIR` in [`main`](https://github.com/zellij-org/zellij/blob/main/src/main.rs#L64-L65)? 

As far as I can see this calls [`std::fs::create_dir`](https://doc.rust-lang.org/std/fs/fn.create_dir.html) which seems to fail if parent directories are not present. I think we want `mkdir -p ...` behaviour here.  [`create_dir_all`](https://doc.rust-lang.org/std/fs/fn.create_dir_all.html) solves that.

**Comment by a-kenji** [comment]
@eschnett 
Do you still have similar problems with darwin specific versions?

**Comment by eschnett** [comment]
The executable in the latest release is now working.

**Comment by a-kenji** [comment]
@eschnett,
Thank you for the confirmation!
