### ISSUE TITLE
Installing and running on Ubuntu 20.04.2

### ISSUE THREAD

**Issue by wnz99** [zellij-org/zellij#367]
Hi, I've just tried to install with `cargo install zellij` and the run on Ubuntu 20.04.2 but I'm getting the following error:

```
RUST_BACKTRACE=full zellij 
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 20, kind: Other, message: "Not a directory" }', /home/whitenoise/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-0.5.1/src/main.rs:51:47
stack backtrace:
   0:     0x561ae3db0290 - std::backtrace_rs::backtrace::libunwind::trace::h87bbdc8ae314e5a4
                               at /build/rustc-n7HJ8w/rustc-1.47.0+dfsg1+llvm/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
   1:     0x561ae3db0290 - std::backtrace_rs::backtrace::trace_unsynchronized::h779de2081f0fe77d
                               at /build/rustc-n7HJ8w/rustc-1.47.0+dfsg1+llvm/library/std/src/../../backtrace/src/backtrace/mod.rs:66
   2:     0x561ae3db0290 - std::sys_common::backtrace::_print_fmt::h7f9f27f2b4d4cdf1
                               at /build/rustc-n7HJ8w/rustc-1.47.0+dfsg1+llvm/library/std/src/sys_common/backtrace.rs:79
   3:     0x561ae3db0290 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf95d19d7937b7307
                               at /build/rustc-n7HJ8w/rustc-1.47.0+dfsg1+llvm/library/std/src/sys_common/backtrace.rs:58
   4:     0x561ae3b82cdf - core::fmt::write::h31ddd5324183dd8d
                               at /build/rustc-n7HJ8w/rustc-1.47.0+dfsg1+llvm/library/core/src/fmt/mod.rs:1082
   5:     0x561ae3da7834 - std::io::Write::write_fmt::h6553ae225ae21934
                               at /build/rustc-n7HJ8w/rustc-1.47.0+dfsg1+llvm/library/std/src/io/mod.rs:1514
   6:     0x561ae3dc5010 - std::sys_common::backtrace::_print::h6d7cde6fb59a3272
                               at /build/rustc-n7HJ8w/rustc-1.47.0+dfsg1+llvm/library/std/src/sys_common/backtrace.rs:61
   7:     0x561ae3dc5010 - std::sys_common::backtrace::print::h024fb5a1f254b027
                               at /build/rustc-n7HJ8w/rustc-1.47.0+dfsg1+llvm/library/std/src/sys_common/backtrace.rs:48
   8:     0x561ae3dc5010 - std::panicking::default_hook::{{closure}}::h008654930ff7c19c
                               at /build/rustc-n7HJ8w/rustc-1.47.0+dfsg1+llvm/library/std/src/panicking.rs:200
   9:     0x561ae3dc5894 - std::panicking::default_hook::h611ef89f1ca4afb7
                               at /build/rustc-n7HJ8w/rustc-1.47.0+dfsg1+llvm/library/std/src/panicking.rs:219
  10:     0x561ae3dc5894 - std::panicking::rust_panic_with_hook::h4dfeaf97568ec250
                               at /build/rustc-n7HJ8w/rustc-1.47.0+dfsg1+llvm/library/std/src/panicking.rs:569
  11:     0x561ae3db0648 - std::panicking::begin_panic_handler::{{closure}}::hf55586f621f9c415
                               at /build/rustc-n7HJ8w/rustc-1.47.0+dfsg1+llvm/library/std/src/panicking.rs:476
  12:     0x561ae3db0614 - std::sys_common::backtrace::__rust_end_short_backtrace::hbddda20e4c1f6fd7
                               at /build/rustc-n7HJ8w/rustc-1.47.0+dfsg1+llvm/library/std/src/sys_common/backtrace.rs:153
  13:     0x561ae3dc468d - rust_begin_unwind
                               at /build/rustc-n7HJ8w/rustc-1.47.0+dfsg1+llvm/library/std/src/panicking.rs:475
  14:     0x561ae3b81090 - core::panicking::panic_fmt::he4c3f055751e8cea
                               at /build/rustc-n7HJ8w/rustc-1.47.0+dfsg1+llvm/library/core/src/panicking.rs:85
  15:     0x561ae3b824e2 - core::result::unwrap_failed::h24cfbc9782f4fe17
                               at /build/rustc-n7HJ8w/rustc-1.47.0+dfsg1+llvm/library/core/src/result.rs:1220
  16:     0x561ae401428e - zellij::main::hb4d9ac3792ffc8c8
  17:     0x561ae3acf783 - std::sys_common::backtrace::__rust_begin_short_backtrace::h3647696c5e4ff596
  18:     0x561ae4013546 - main
  19:     0x7febcaf5c0b3 - __libc_start_main
  20:     0x561ae3aca74e - _start
  21:                0x0 - <unknown>

```

**Comment by a-kenji** [comment]
Thank you for filing this issue! 
Could be related to #363.

**Comment by SaintFenix** [comment]
I've attempted the build with V0.6 and didn't get any errors.

@wnz99 if you have a chance could you give it another shot with the current build?

**Comment by wnz99** [comment]
apologies for the delayed reply. I can confirm that now both `cargo install zellij` and the binary in https://github.com/zellij-org/zellij/releases/tag/v0.11.0 works.

**Comment by a-kenji** [comment]
@wnz99 
No problem! Thank you for checking. 
I am happy that it works now for you!
Please do reach out in the future if you have any issues.
