### ISSUE TITLE
Doesn't start when used by multiple users

### ISSUE THREAD

**Issue by muffin4** [zellij-org/zellij#417]
## Description

When starting `zellij` after it has been started (and optionally closed) by another user I get this error message and the program exits with error code 1:

```
Originating Thread(s):

Error: thread 'ipc_server' panicked at 'could not listen on ipc socket: Os { code: 98, kind: AddrInUse, message: "Address already in use" }': /home/u2/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-0.6.0/src/common/mod.rs:589
   0: zellij::common::errors::handle_panic
   1: std::panicking::rust_panic_with_hook
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:595:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:497:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:141:18
   4: rust_begin_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
   5: core::panicking::panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:92:14
   6: core::option::expect_none_failed
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/option.rs:1300:5
   7: std::sys_common::backtrace::__rust_begin_short_backtrace
   8: core::ops::function::FnOnce::call_once{{vtable.shim}}
   9: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys/unix/thread.rs:71:17
  10: start_thread
  11: clone
```

When running as `zellij --debug` the gui seems to load and the cursor is blinking, but my bash prompt doesn't show up and zellij seems to be stuck and doesn't respond to any of my inputs.

I noticed that there's a `/tmp/zellij/` directory owned by the first user, that the second user doesn't have access to, but that path is hardcoded in `src/common/utils/consts.rs`.

## Suggestion

It might be a good idea to use a runtime path similar to `$XDG_RUNTIME_DIR` instead of `/tmp` (or even `std::env::temp_dir`).

## Information

- zellij 0.6.0
- Arch Linux 5.11.16-zen1-1-zen

**Comment by imsnif** [comment]
Thanks for the report! This is indeed an issue with the ownership of the temporary folder. We are solving it as part of an upcoming PR: https://github.com/zellij-org/zellij/pull/223

**Comment by khs26** [comment]
This does now work except in scenarios using su. A user `user1` running zellij cannot then open another terminal window, and run:
- `su user2`
- `zellij`

It looks like this might be due to the reliance on `XDG_RUNTIME_DIR`, which is only set at login and not overwritten by changing users without starting a new login shell.

**Comment by khs26** [comment]
Resolved as part of #223.
