### ISSUE TITLE
Closing a pane that's in fullscreen results in an error

### ISSUE THREAD

**Issue by denismaxim0v** [zellij-org/zellij#48]
Steps to reproduce:
- Open a new pane
- Toggle to full screen
- Try to close with either ctrl-x or 'exit'
results in:
```
thread 'screen' panicked at 'called `Option::unwrap()` on a `None` value', src/screen.rs:355:59                                                           
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace                                                                         
thread 'async-std/runtime' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', src/pty_bus.rs:251:18                                        
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any', src/main.rs:420:31
```

**Comment by imsnif** [comment]
@denismaxim0v - I can no longer reproduce this. Could it be that we fixed it at some point?

**Comment by denismaxim0v** [comment]
Yes, I guess it was fixed
