### ISSUE TITLE
Zellij crashed when scrolling

### ISSUE THREAD

**Issue by tw4452852** [zellij-org/zellij#649]
When I scrolled inside Zellij (no matter in locked mode or normal mode), it sometimes crashed with following backtrace:

```
Error occured in server:
Originating Thread(s):
1. screen_thread: HandlePtyBytes

Error: thread 'screen' panicked at 'called `Option::unwrap()` on a `None` value': zellij-server/src/panes/grid.rs:907
   0: zellij_utils::errors::handle_panic
             at zellij-utils/src/errors.rs:24:21
   1: zellij_server::start_server::{{closure}}
             at zellij-server/src/lib.rs:139:13
   2: std::panicking::rust_panic_with_hook
             at /rustc/53fd98ca776cb875bc9e5514f56b52eb74f9e7a9/library/std/src/panicking.rs:626:17
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/53fd98ca776cb875bc9e5514f56b52eb74f9e7a9/library/std/src/panicking.rs:517:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/53fd98ca776cb875bc9e5514f56b52eb74f9e7a9/library/std/src/sys_common/backtrace.rs:141:18
   5: rust_begin_unwind
             at /rustc/53fd98ca776cb875bc9e5514f56b52eb74f9e7a9/library/std/src/panicking.rs:515:5
   6: core::panicking::panic_fmt
             at /rustc/53fd98ca776cb875bc9e5514f56b52eb74f9e7a9/library/core/src/panicking.rs:92:14
   7: core::panicking::panic
             at /rustc/53fd98ca776cb875bc9e5514f56b52eb74f9e7a9/library/core/src/panicking.rs:50:5
   8: core::option::Option<T>::unwrap
             at /rustc/53fd98ca776cb875bc9e5514f56b52eb74f9e7a9/library/core/src/option.rs:722:21
   9: zellij_server::panes::grid::Grid::replace_characters_in_line_after_cursor
             at zellij-server/src/panes/grid.rs:905:9
  10: <zellij_server::panes::grid::Grid as vte::Perform>::csi_dispatch
             at zellij-server/src/panes/grid.rs:1549:21
  11: vte::Parser::perform_action
             at /home/tw/.cargo/registry/src/github.com-1ecc6299db9ec823/vte-0.10.1/src/lib.rs:302:17
  12: vte::Parser::perform_state_change
             at /home/tw/.cargo/registry/src/github.com-1ecc6299db9ec823/vte-0.10.1/src/lib.rs:175:17
  13: vte::Parser::advance
             at /home/tw/.cargo/registry/src/github.com-1ecc6299db9ec823/vte-0.10.1/src/lib.rs:130:9
  14: <zellij_server::panes::terminal_pane::TerminalPane as zellij_server::tab::Pane>::handle_pty_bytes
             at zellij-server/src/panes/terminal_pane.rs:91:13
  15: zellij_server::tab::Tab::handle_pty_bytes
             at zellij-server/src/tab.rs:841:13
  16: zellij_server::screen::screen_thread_main
             at zellij-server/src/screen.rs:469:21
  17: zellij_server::init_session::{{closure}}
             at zellij-server/src/lib.rs:366:17
  18: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/53fd98ca776cb875bc9e5514f56b52eb74f9e7a9/library/std/src/sys_common/backtrace.rs:125:18
  19: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}
             at /rustc/53fd98ca776cb875bc9e5514f56b52eb74f9e7a9/library/std/src/thread/mod.rs:476:17
  20: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/53fd98ca776cb875bc9e5514f56b52eb74f9e7a9/library/std/src/panic.rs:347:9
  21: std::panicking::try::do_call
             at /rustc/53fd98ca776cb875bc9e5514f56b52eb74f9e7a9/library/std/src/panicking.rs:401:40
  22: __rust_try
  23: std::panicking::try
             at /rustc/53fd98ca776cb875bc9e5514f56b52eb74f9e7a9/library/std/src/panicking.rs:365:19
  24: std::panic::catch_unwind
             at /rustc/53fd98ca776cb875bc9e5514f56b52eb74f9e7a9/library/std/src/panic.rs:434:14
  25: std::thread::Builder::spawn_unchecked::{{closure}}
             at /rustc/53fd98ca776cb875bc9e5514f56b52eb74f9e7a9/library/std/src/thread/mod.rs:475:30
  26: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/53fd98ca776cb875bc9e5514f56b52eb74f9e7a9/library/core/src/ops/function.rs:227:5
  27: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/53fd98ca776cb875bc9e5514f56b52eb74f9e7a9/library/alloc/src/boxed.rs:1572:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/53fd98ca776cb875bc9e5514f56b52eb74f9e7a9/library/alloc/src/boxed.rs:1572:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/53fd98ca776cb875bc9e5514f56b52eb74f9e7a9/library/std/src/sys/unix/thread.rs:74:17
  28: start_thread
             at /builddir/glibc-2.32/nptl/pthread_create.c:463:8
  29: __GI___clone
             at /builddir/glibc-2.32/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by imsnif** [comment]
Is this `0.15.0` or from `main`, or?

**Comment by imsnif** [comment]
Also - while scrolling, is input being sent to the pane? (eg. tailing a file)
That's of course still a bug, but that's at least one we know of :)

**Comment by tw4452852** [comment]
Hi @imsnif ,

I used fde38dcb446f7f2071ae8d18b18ea25a04ef22ae from main branch.
What I did is just cat a large file and the crash happened during scrolling up with the mouse (
same in scrolling mode).

And I did an initial check, the culprit is located, I worked out [a fix](https://github.com/tw4452852/zellij/commit/95b97c8dcc7df44663b72d270288032e799eb93d) for this, but it will make another unit test fail.

**Comment by imsnif** [comment]
So, funnily enough my friend, I'm working on *exactly* this issue right now, and I swear I have those exact same lines in my patch ;P I'm doing this as part of a more general fix for scrolling which is a little broken at the moment.

The test it breaks is the `lines_below` mouse copy one, right? I fixed it in my branch.

So, good news: I will be inadvertently fixing this very soon.

**Comment by tw4452852** [comment]
Wow, what a coincidence:) 
Yes, that's exactly the failure test case. Hope for your patch 😉!

**Comment by imsnif** [comment]
In any case, this shouldn't be happening (I hope!!) in the latest release version. Just got this and some other bugs to iron out in main before we release a new version. Thanks for your vigilance in any case :)

**Comment by imsnif** [comment]
Just merged a fix to this in main. Closing this issue.
