### ISSUE TITLE
`zellij attach -c` fails if you haven't started zellij already

### ISSUE THREAD

**Issue by colemickens** [zellij-org/zellij#960]
Note that I clear cache/local state first. (which was needed after some internal color changes, maybe indicating that there's another latent bug - maybe zellij needs to clear it's cache/local state sometimes?)

```
cole@porty ~
❯ rm -rf ~/.cache/zellij; rm -rf ~/.local/share/zellij; zellij attach -c

Error occurred in server:
Originating Thread(s):
1. ipc_server: NewClient
2. pty_thread: NewTab
3. screen_thread: NewTab
4. plugin_thread: Load

Error: thread 'wasm' panicked at 'Cannot resolve wasm bytes for plugin PluginConfig { path: "tab-bar", run: Pane(None), _allow_exec_host_cmd: false, location: Zellij(PluginTag("tab-bar")) }': zellij-server/src/wasm_vm.rs:184
   0: zellij_utils::errors::handle_panic
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: zellij_server::wasm_vm::start_plugin::{{closure}}
   7: zellij_server::wasm_vm::start_plugin
   8: zellij_server::wasm_vm::wasm_thread_main
   9: std::sys_common::backtrace::__rust_begin_short_backtrace
  10: core::ops::function::FnOnce::call_once{{vtable.shim}}
  11: std::sys::unix::thread::Thread::new::thread_start
  12: start_thread
  13: __clone

Error occurred in server:
Originating Thread(s):
1. ipc_server: NewClient
2. pty_thread: NewTab
3. screen_thread: NewTab
4. plugin_thread: Load

Error: thread 'wasm' panicked at 'Cannot resolve wasm bytes for plugin PluginConfig { path: "tab-bar", run: Pane(None), _allow_exec_host_cmd: false, location: Zellij(PluginTag("tab-bar")) }': zellij-server/src/wasm_vm.rs:184
   0: zellij_utils::errors::handle_panic
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: zellij_server::wasm_vm::start_plugin::{{closure}}
   7: zellij_server::wasm_vm::start_plugin
   8: zellij_server::wasm_vm::wasm_thread_main
   9: std::sys_common::backtrace::__rust_begin_short_backtrace
  10: core::ops::function::FnOnce::call_once{{vtable.shim}}
  11: std::sys::unix::thread::Thread::new::thread_start
  12: start_thread
  13: __clone

cole@porty ~
❯ zellij --version
zellij 0.22.0
```

**Comment by colemickens** [comment]
To be extra explicit too, I don't think this is about client/server mismatch:

```
❯ ps aux | grep zellij
cole     1177830  0.0  0.0 223484  1636 pts/0    S+   11:28   0:00 grep zellij
```

**Comment by jaeheonji** [comment]
Hi! @colemickens
This is a problem that default assets cannot be created when the `-c` option is used. Thanks for finding the bug!
