### ISSUE TITLE
Panic closing last tab in multiuser session

### ISSUE THREAD

**Issue by neurocyte** [zellij-org/zellij#988]
With three clients attached to a multiuser session, closing the final tab, and thereby exiting all three clients at once sometimes causes this panic.

```
Error occurred in server:
Originating Thread(s):
1. screen_thread: Render

Error: thread 'screen' panicked at 'called `Option::unwrap()` on a `None` value': zellij-server/src/screen.rs:241
   0: zellij_utils::errors::handle_panic
   1: std::panicking::rust_panic_with_hook
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:628:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:519:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:139:18
   4: rust_begin_unwind
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:517:5
   5: core::panicking::panic_fmt
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:100:14
   6: core::panicking::panic
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:50:5
   7: zellij_server::screen::Screen::close_tab_at_index
   8: zellij_server::screen::Screen::render
   9: zellij_server::screen::screen_thread_main
  10: std::sys_common::backtrace::__rust_begin_short_backtrace
  11: core::ops::function::FnOnce::call_once{{vtable.shim}}
  12: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/alloc/src/boxed.rs:1691:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/alloc/src/boxed.rs:1691:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys/unix/thread.rs:106:17
  13: start_thread
  14: __GI___clone
```

**Basic information**

`zellij --version`: main branch tip (04fe184)
`tput lines`: various
`tput cols`: various
`uname -av`: Linux 5.15.12-1-MANJARO x86_64 

**Further information**
It does not always panic. It may depend on how many tabs are open (I triggered it a few time with 8) and which tabs are active on the three clients before starting to close them.

**Comment by imsnif** [comment]
Just merged a fix for this into main. Thanks for finding all the issues! :D
Please keep them coming.
